mysql:
  host: '127.0.0.1'
  port: '3306'
  username: 'root'
  password: 'root'
  database: 'medical_info'
  charset: 'utf8mb4'
  parse-time: true
  loc: 'Local'

baidu-ocr:
  ak: 'twSZO6Wo1BzQbH5VvHjMRh24'
  sk: '8iqWLVXpXrYgPdtU1PF8M6RjY0OyBjSU'
  token-url: 'https://aip.baidubce.com/oauth/2.0/token'
  ocr-url: 'https://aip.baidubce.com/rest/2.0/ocr/v1/accurate'

qiniu-kodo:
  path: 'codex_file'
  bucket: 'myfiledb'
  domain: 'tfzjbyhvy.hb-bkt.clouddn.com'
  access-key: 'hMDX2NQ5YFULG8q0cd0cAadlj83u1NIFPdPlbiMX'
  secret-key: 'VDL7K2W6Et9kgxiNhiNMh1rZP4vVg1SoLRx3R0ST'
